### ISSUE TITLE
Secret::random()

### ISSUE THREAD

**Issue by thekid** [xp-framework/core#142]
In my code I needed a random initial password, so I used `base64_encode(openssl_random_pseudo_bytes(12))`. I think a good place for this might be the `util.Secret` class:

```php
$secret= Secret::random(12);
$value= $secret->reveal();
```

See also http://php.net/manual/en/function.random-bytes.php (PHP 7 only!)

**Comment by thekid** [comment]
Could replace https://github.com/xp-forge/google-authenticator/blob/master/src/main/php/com/google/authenticator/Secrets.class.php

**Comment by thekid** [comment]
> a  good place for this might be the util.Secret class

Thinking twice it may not be the ideal place... maybe a `Random` class would be better:

* [System.Random](https://msdn.microsoft.com/de-de/library/system.random(v=vs.110).aspx) - .NET Framework
* [java.util.Random](http://docs.oracle.com/javase/8/docs/api/java/util/Random.html) - Java 8

**Comment by kiesel** [comment]
:+1: for *Random*
