### ISSUE TITLE
HHVM support

### ISSUE THREAD

**Issue by thekid** [xp-framework/core#176]
```bash
$ XP_RT=hhvm xp -v

Fatal error: Uncaught exception 'Exception' with message 'This version of the XP Framework 
requires PHP 7.0.0+, have PHP 5.6.99-hhvm'
```

**Comment by thekid** [comment]
> ... the upcoming 3.11.0 stable release will be the first release of HHVM with support for the major PHP 7 features.
*(source: http://hhvm.com/blog/10859/php-7-support)*

This means the checks should be on:

* PHP_VERSION_ID >= 70000
* defined('HHVM_VERSION_ID') && HHVM_VERSION_ID >= 31100

**Comment by thekid** [comment]
Let's see how this does on Travis-CI...

**Comment by thekid** [comment]
OK, here are some of the issues:

* `namespace lang; class ... extends Throwable` raises: *Fatal error: Uncaught Error: Class lang\T may not inherit from interface (__SystemLib\Throwable)*. HHVM seems to prefer its builtin classes over the `Throwable` class declared in the `lang` namespace. *Fixed by fully qualifying parent class names*
* HHVM doesn't catch exceptions when using `catch (\Throwable $t)` - unlike PHP, the *Throwable* type is not inside global namespace - *can be fixed by adding `catch (\__SystemLib\Throwable $t)` *

**Comment by thekid** [comment]
HHVM branched off, too much of a hassle right now.

**Comment by fredemmott** [comment]
- PHP version ID: as you found, needs the ini flag setting
 - Throwable: should be fixed in 3.20 - if not, please file an issue against HHVM and mention me in the comment: https://github.com/facebook/hhvm/commit/29fc86f9ddefc918549c201ebe5ee8a978efde44
 - Strict mode: should also be fixed in 3.20 - if not, file an issue, but I'm not the right person for it: https://github.com/facebook/hhvm/commit/f02a287591d35ed4d846751f18d211272b859a66

Sadly, travis is a pain to use with HHVM: HHVM's only supported by Travis on Ubuntu 14.04, and recent versions of HHVM require 16.04 or newer. You can use docker, but this would likely require a change to your PHP testing too, so might not be worth it.

Docker travis example:

https://github.com/facebook/xhp-lib/blob/master/.travis.yml
https://github.com/facebook/xhp-lib/blob/master/.travis.sh

**Comment by thekid** [comment]
> Strict mode: should also be fixed in 3.20 - if not, file an issue

There actually already is one for it: https://github.com/facebook/hhvm/issues/7709

**Comment by thekid** [comment]
> Throwable: should be fixed in 3.20 

It is, thanks @fredemmott!

**Comment by thekid** [comment]
> PHP version ID: as you found, needs the ini flag setting

Nice, HHVM 3.20 now also returns a PHP7-ish version number instead of 5.6.99

```bash
$ hhvm --version
HipHop VM 3.20.2 (rel)
Compiler: tags/HHVM-3.20.2-0-gad133f299ece0e45db8536473a8ef77cc4612ae3
Repo schema: 962ff68f0831a12b292f0eb9acd17f705a904446

$ XP_RT=hhvm xp -w '[PHP_VERSION_ID, phpversion()]'
[70199, "7.1.99-hhvm"]
```

**Comment by thekid** [comment]
Giving it a try:

```bash
$ XP_RT=hhvm xp -cp test.xar xp.unittest.TestRunner src/test/config/unittest/core.ini
# ...
terminate called without an active exception
Core dumped: Aborted
Stack trace in /tmp/stacktrace.1108.log

$ cat /tmp/stacktrace.1108.log
Host: slate
ProcessID: 1108
ThreadID: 140197943919552
ThreadPID: 1108
Name: /usr/bin/xp
Type: Aborted
Runtime: hhvm
Version: tags/HHVM-3.20.2-0-gad133f299ece0e45db8536473a8ef77cc4612ae3
DebuggerCount: 0

Arguments: /usr/bin/class-main.php xp.unittest.TestRunner src/test/config/unittest/core.ini
ThreadType: CLI

# 0  0000000003508796
# 1  0000000001167f92
# 2  00007f825e971390
# 3  00007f8257d95428
# 4  00007f8257d9702a
# 5  00007f82586ef84d
# 6  00007f82586ed6b6
# 7  00007f82586ed701
# 8  00000000011c59e2
# 9  0000000010bc02a4
# 10 000000000a1c829c
# 11 000000000640029e
# 12 0000000002000554
# 13 00000000020f321a
# 14 00000000010caea8
# 15 0000000002cab277
# 16 000000000a07377c
# 17 000000000a0736bd
# 18 000000000a072c2e
# 19 000000000a072485
# 20 000000000a06f720
# 21 000000000e0000c0
# 22 000000000e0000c0
# 23 000000000e0000c0
# 24 000000000640029e
# 25 0000000002000554
# 26 00000000020f321a
# 27 00000000010cb505
# 28 00000000010cbba1
# 29 0000000003510348
# 30 00000000035106c9
# 31 00000000013d575b
# 32 00000000013d5fcb
# 33 00000000013eae07
# 34 00000000013eca37
# 35 00000000011b7938
# 36 0000000000a10f38
# 37 00007f8257d80830
# 38 0000000000a0c0d9

PHP Stacktrace:

#0  lang\Throwable::printStackTrace() called at [/mnt/.../src/test/php/net/xp_framework/unittest/core/ExceptionsTest.class.php:118]
#1  net\xp_framework\unittest\core\ExceptionsTest->printStackTrace()
#2  ReflectionMethod->invokeArgs() called at [/mnt/.../src/main/php/lang/reflect/Method.class.php:88]
#3  lang\reflect\Method->invoke() called at [xar:///mnt/.../test.xar?unittest/TestSuite.class.php:317]
#4  unittest\TestSuite->runInternal() called at [xar:///mnt/.../test.xar?unittest/TestSuite.class.php:529]
#5  unittest\TestSuite->run() called at [xar:///mnt/.../test.xar?xp/unittest/TestRunner.class.php:376]
#6  xp\unittest\TestRunner->run() called at [xar:///mnt/.../test.xar?xp/unittest/TestRunner.class.php:386]
#7  xp\unittest\TestRunner::main() called at [/usr/bin/class-main.php:374]
```

**Comment by thekid** [comment]
Some more small incompatibilities:

* net.xp_framework.unittest.io.streams.Bz2CompressingOutputStreamTest fails because the stream wrapper doesn't honor the *blocks* setting: `stream_filter_append($this->out, 'bzip2.compress', STREAM_FILTER_WRITE, ['blocks' => $level])`

**Comment by thekid** [comment]
Added a workaround for the hphp_(get|set)_property problem by calling them directly. In essence, this is what I'm doing:

```php
if (defined('HHVM_VERSION_ID')) {
  self::$read= function($class, $reflect, $instance, $public) {
    if (null === $instance) {
      return hphp_get_static_property($class, $reflect->getName(), !$public);
    } else {
      return hphp_get_property($instance, $class, $reflect->getName());
    }
  };
  self::$write= function($class, $reflect, $instance, $value, $public) {
    if (null === $instance) {
      return hphp_set_static_property($class, $reflect->getName(), $value, !$public);
    } else {
      return hphp_set_property($instance, $class, $reflect->getName(), $value);
    }
  };
} else {
  self::$read= function($class, $reflect, $instance, $public) {
    $public || $reflect->setAccessible(true);
    return $reflect->getValue($instance);
  };
  self::$write= function($class, $reflect, $instance, $value, $public) {
    $public || $reflect->setAccessible(true);
    return $reflect->setValue($instance, $value);
  };
}
```

Adding a small overhead with the closure function call, though.

Documentation for these functions is available [in ext/reflection/ext_reflection-internals-functions.php](https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext/reflection/ext_reflection-internals-functions.php)

**Comment by thekid** [comment]
Added `@action(new IgnoredOnHHVM())` to the tests for void return types and variadics with type, see xp-framework/core@9868a57

* * *

This gets us to:

```bash
$ XP_RT=hhvm xp -cp test.xar xp.unittest.TestRunner src/test/config/unittest/core.ini
# ...
×: 2117/2196 run (79 skipped), 2115 succeeded, 2 failed
Memory used: 4096.00 kB (4096.00 kB peak)
Time taken: 49.337 seconds
```

**Comment by thekid** [comment]
"Cherry-picked" https://github.com/xp-framework/core/pull/178/commits/c5a7000cfe856c42b6ecf23d46a9165df9e9fbe3 to fix variadic parameters always returning `array` on HHVM in xp-framework/core@569b3a1.

This gets us to:

```bash
$ XP_RT=hhvm xp -cp test.xar xp.unittest.TestRunner src/test/config/unittest/core.ini
# ...
×: 2117/2196 run (79 skipped), 2116 succeeded, 1 failed
Memory used: 4096.00 kB (4096.00 kB peak)
Time taken: 50.479 seconds
```

**Almost!**

**Comment by thekid** [comment]
This resulted from PHP throwing an `Error` (which gets wrapped into a lang.Error), while HHVM throws as `BadMethodCallException` (which gets wrapped into a lang.XPException). Addressed this in `lang.Throwable::wrap()`, which now does:

```php
if ($e instanceof self) {
  return $e;
} else if ($e instanceof \BadMethodCallException) {
  $wrapped= new Error($e->getMessage(), $e->getPrevious(), false);
} else if ($e instanceof \Exception) {
  $wrapped= new XPException($e->getMessage(), $e->getPrevious(), false);
} else if ($e instanceof \Throwable) {
  $wrapped= new Error($e->getMessage(), $e->getPrevious(), false);
} else {
  throw new IllegalArgumentException('Given argument ...');
}
```

**Comment by thekid** [comment]
Example for older HHVM versions:

```bash
$ XP_RT=hhvm xp -v

Fatal error: Uncaught exception 'Exception' with message 'This version of the XP Framework
requires HHVM 3.20.2+, have HHVM 3.18.0'
```

**Comment by thekid** [comment]
> HHVM branched off to feature/hhvm-7 branch, too much of a hassle right now.

This branch has now been removed again, HHVM support is back.

**Comment by thekid** [comment]
Here are some problems from running the entire test  suite:

```
F unittest.TestAssertionFailed(test= net.xp_framework.unittest.io.PathTest::normalize_uppercases_drive_letter, time= 0.072 seconds) {
  unittest.AssertionFailedError{ expected ["C:/test"] but was ["c:/test"] using: 'equals' }
    at unittest.TestCase::assertEquals() [line 314 of PathTest.class.php]
    at net.xp_framework.unittest.io.PathTest::normalize_uppercases_drive_letter() [line 0 of StackTraceElement.class.php]
    at ReflectionMethod::invokeArgs() [line 88 of Method.class.php]
    at lang.reflect.Method::invoke() [line 317 of TestSuite.class.php]
    at unittest.TestSuite::runInternal() [line 529 of TestSuite.class.php]
    at unittest.TestSuite::run() [line 376 of TestRunner.class.php]
    at xp.unittest.TestRunner::run() [line 386 of TestRunner.class.php]
    at xp.unittest.TestRunner::main() [line 374 of class-main.php]

 }
F unittest.TestAssertionFailed(test= net.xp_framework.unittest.io.PathTest::relative_to("c:/Windows", "C:/", "Windows"), time= 0.002 seconds) {
  unittest.AssertionFailedError{ expected ["Windows"] but was ["../../c:/Windows"] using: 'equals' }
    at unittest.TestCase::assertEquals() [line 353 of PathTest.class.php]
    at net.xp_framework.unittest.io.PathTest::relative_to() [line 0 of StackTraceElement.class.php]
    at ReflectionMethod::invokeArgs() [line 88 of Method.class.php]
    at lang.reflect.Method::invoke() [line 317 of TestSuite.class.php]
    at unittest.TestSuite::runInternal() [line 529 of TestSuite.class.php]
    at unittest.TestSuite::run() [line 376 of TestRunner.class.php]
    at xp.unittest.TestRunner::run() [line 386 of TestRunner.class.php]
    at xp.unittest.TestRunner::main() [line 374 of class-main.php]

 }
F unittest.TestAssertionFailed(test= net.xp_framework.unittest.io.PathTest::relative_to("C:\Windows", "c:", "Windows"), time= 0.000 seconds) {
  unittest.AssertionFailedError{ expected ["Windows"] but was ["../C:\Windows"] using: 'equals' }
    at unittest.TestCase::assertEquals() [line 353 of PathTest.class.php]
    at net.xp_framework.unittest.io.PathTest::relative_to() [line 0 of StackTraceElement.class.php]
    at ReflectionMethod::invokeArgs() [line 88 of Method.class.php]
    at lang.reflect.Method::invoke() [line 317 of TestSuite.class.php]
    at unittest.TestSuite::runInternal() [line 529 of TestSuite.class.php]
    at unittest.TestSuite::run() [line 376 of TestRunner.class.php]
    at xp.unittest.TestRunner::run() [line 386 of TestRunner.class.php]
    at xp.unittest.TestRunner::main() [line 374 of class-main.php]

 }
```

**Comment by thekid** [comment]
OK, Travis-CI gives us:

```bash
$ hhvm --version
HipHop VM 3.18.3 (rel)
Compiler: tags/HHVM-3.18.3-0-g1ddd4af7b1342c20635afbdc67701fbcbdf97bfa
Repo schema: 61b13efcfd4e2fabea72495f96208746a568a688
```
*See https://travis-ci.org/xp-framework/core/jobs/241581199*

This won't work, neither will `hhvm-nightly`, which is [even older(!)](https://travis-ci.org/xp-framework/core/jobs/241581843)

**Comment by thekid** [comment]
✅ Restored unittests success by running HHVM in Docker: https://travis-ci.org/xp-framework/core/jobs/241590443

**Comment by thekid** [comment]
https://travis-ci.org/xp-framework/core/jobs/241601020

**Comment by thekid** [comment]
Interesting: 

> PHP7 is charting a new course away from PHP5, and we want to do the same, via a renewed focus on Hack. Consequently, HHVM will not aim to target PHP7. The HHVM team believes that we have a clear path toward making Hack a fantastic language for web development, untethered from its PHP origins. 

http://hhvm.com/blog/2017/09/18/the-future-of-hhvm.html
